services:
  - type: web
    name: ticket-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python admin.py
    rootDir: admin
    domains:
      - admin.mypassdelivery.com

  - type: web
    name: ticket-viewer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python viewer.py
    rootDir: viewer
    domains:
      - mypassdelivery.com
